[package]
name = "api-naroden-org"
version = "0.0.5"
readme = "README.md"
edition = "2021"

[dependencies]
poem = "3.0.0"
poem-openapi = { version = "5.1.1", features = ["swagger-ui"] }
poem-grants = "3.0.1"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
base64 = "0.21.7"
serde_json = "1.0.116"
serde = { version = "1.0.199", features = ["derive"] }
surrealdb = { version = "2.0.4", features = ["protocol-http"] }
argon2 = "0.5.3"
envconfig = "0.10.0"
jsonwebtoken = "9.3.0"
chrono = "0.4.38"
once_cell = "1.19.0"
strum_macros = "0.26.4"
log = "0.4.21"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true
codegen-units = 1