[package]
name = "api-naroden-org"
version = "0.0.2"
readme = "README.md"
edition = "2021"

[dependencies]
poem = "3.0.0"
poem-openapi = { version = "5.0.0", features = ["swagger-ui"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
base64 = "0.21.7"
serde_json = "1.0.116"
serde = { version = "1.0.199", features = ["derive"] }
surrealdb = "1.4.2"
argon2 = "0.5.3"
envconfig = "0.10.0"
jsonwebtoken = "9.3.0"
chrono = "0.4.38"
once_cell = "1.19.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true
codegen-units = 1